// Generated by gencpp from file gbrobot/deskInserterRequest.msg
// DO NOT EDIT!


#ifndef GBROBOT_MESSAGE_DESKINSERTERREQUEST_H
#define GBROBOT_MESSAGE_DESKINSERTERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gbrobot
{
template <class ContainerAllocator>
struct deskInserterRequest_
{
  typedef deskInserterRequest_<ContainerAllocator> Type;

  deskInserterRequest_()
    : deskID(0)  {
    }
  deskInserterRequest_(const ContainerAllocator& _alloc)
    : deskID(0)  {
  (void)_alloc;
    }



   typedef uint64_t _deskID_type;
  _deskID_type deskID;





  typedef boost::shared_ptr< ::gbrobot::deskInserterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gbrobot::deskInserterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct deskInserterRequest_

typedef ::gbrobot::deskInserterRequest_<std::allocator<void> > deskInserterRequest;

typedef boost::shared_ptr< ::gbrobot::deskInserterRequest > deskInserterRequestPtr;
typedef boost::shared_ptr< ::gbrobot::deskInserterRequest const> deskInserterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gbrobot::deskInserterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gbrobot::deskInserterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gbrobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gbrobot::deskInserterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gbrobot::deskInserterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gbrobot::deskInserterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gbrobot::deskInserterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gbrobot::deskInserterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gbrobot::deskInserterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gbrobot::deskInserterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed65048fee4c00c2db9c6f0e9a7771ee";
  }

  static const char* value(const ::gbrobot::deskInserterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed65048fee4c00c2ULL;
  static const uint64_t static_value2 = 0xdb9c6f0e9a7771eeULL;
};

template<class ContainerAllocator>
struct DataType< ::gbrobot::deskInserterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gbrobot/deskInserterRequest";
  }

  static const char* value(const ::gbrobot::deskInserterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gbrobot::deskInserterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 deskID\n\
";
  }

  static const char* value(const ::gbrobot::deskInserterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gbrobot::deskInserterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.deskID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct deskInserterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gbrobot::deskInserterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gbrobot::deskInserterRequest_<ContainerAllocator>& v)
  {
    s << indent << "deskID: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.deskID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GBROBOT_MESSAGE_DESKINSERTERREQUEST_H
