// Generated by gencpp from file gbrobot/navigateRequest.msg
// DO NOT EDIT!


#ifndef GBROBOT_MESSAGE_NAVIGATEREQUEST_H
#define GBROBOT_MESSAGE_NAVIGATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gbrobot
{
template <class ContainerAllocator>
struct navigateRequest_
{
  typedef navigateRequest_<ContainerAllocator> Type;

  navigateRequest_()
    : desk(0)  {
    }
  navigateRequest_(const ContainerAllocator& _alloc)
    : desk(0)  {
  (void)_alloc;
    }



   typedef uint64_t _desk_type;
  _desk_type desk;





  typedef boost::shared_ptr< ::gbrobot::navigateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gbrobot::navigateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct navigateRequest_

typedef ::gbrobot::navigateRequest_<std::allocator<void> > navigateRequest;

typedef boost::shared_ptr< ::gbrobot::navigateRequest > navigateRequestPtr;
typedef boost::shared_ptr< ::gbrobot::navigateRequest const> navigateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gbrobot::navigateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gbrobot::navigateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gbrobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg', '/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gbrobot::navigateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gbrobot::navigateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gbrobot::navigateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gbrobot::navigateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gbrobot::navigateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gbrobot::navigateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gbrobot::navigateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25d2f54ea8f8d764186091003fcf3502";
  }

  static const char* value(const ::gbrobot::navigateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25d2f54ea8f8d764ULL;
  static const uint64_t static_value2 = 0x186091003fcf3502ULL;
};

template<class ContainerAllocator>
struct DataType< ::gbrobot::navigateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gbrobot/navigateRequest";
  }

  static const char* value(const ::gbrobot::navigateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gbrobot::navigateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 desk\n\
";
  }

  static const char* value(const ::gbrobot::navigateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gbrobot::navigateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.desk);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct navigateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gbrobot::navigateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gbrobot::navigateRequest_<ContainerAllocator>& v)
  {
    s << indent << "desk: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.desk);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GBROBOT_MESSAGE_NAVIGATEREQUEST_H
