// Generated by gencpp from file gbrobot/reset.msg
// DO NOT EDIT!


#ifndef GBROBOT_MESSAGE_RESET_H
#define GBROBOT_MESSAGE_RESET_H

#include <ros/service_traits.h>


#include <gbrobot/resetRequest.h>
#include <gbrobot/resetResponse.h>


namespace gbrobot
{

struct reset
{

typedef resetRequest Request;
typedef resetResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct reset
} // namespace gbrobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gbrobot::reset > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::gbrobot::reset&) { return value(); }
};

template<>
struct DataType< ::gbrobot::reset > {
  static const char* value()
  {
    return "gbrobot/reset";
  }

  static const char* value(const ::gbrobot::reset&) { return value(); }
};


// service_traits::MD5Sum< ::gbrobot::resetRequest> should match 
// service_traits::MD5Sum< ::gbrobot::reset > 
template<>
struct MD5Sum< ::gbrobot::resetRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gbrobot::reset >::value();
  }
  static const char* value(const ::gbrobot::resetRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gbrobot::resetRequest> should match 
// service_traits::DataType< ::gbrobot::reset > 
template<>
struct DataType< ::gbrobot::resetRequest>
{
  static const char* value()
  {
    return DataType< ::gbrobot::reset >::value();
  }
  static const char* value(const ::gbrobot::resetRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gbrobot::resetResponse> should match 
// service_traits::MD5Sum< ::gbrobot::reset > 
template<>
struct MD5Sum< ::gbrobot::resetResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gbrobot::reset >::value();
  }
  static const char* value(const ::gbrobot::resetResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gbrobot::resetResponse> should match 
// service_traits::DataType< ::gbrobot::reset > 
template<>
struct DataType< ::gbrobot::resetResponse>
{
  static const char* value()
  {
    return DataType< ::gbrobot::reset >::value();
  }
  static const char* value(const ::gbrobot::resetResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GBROBOT_MESSAGE_RESET_H
